#!/usr/bin/env julia

# Base-only independent golden generator for the U250 fixture accelerator.
# It deliberately uses the string/Dict orbit implementation already used by
# the Darwin Atlas Julia differential validator, not the FPGA base-4 kernel.

length(ARGS) == 2 || error("usage: generate_fixture_header.jl <cases.tsv> <output.hpp>")

include(joinpath(@__DIR__, "..", "..", "..", "julia", "scripts", "window_pipeline_core.jl"))

const REPLICATES = 8
const METRIC_COUNT = 18
const MAX_WINDOW = 16

function parse_cases(path::String)
    rows = readlines(path)
    isempty(rows) && error("empty fixture")
    rows[1] == "case_id\tparameters_sha256\twindow_start\trecord_index\twindow_size\tmin_kmer_effective_count\tbases" ||
        error("fixture header drift")
    cases = NamedTuple[]
    for row in rows[2:end]
        f = split(row, '\t'; keepempty=true)
        length(f) == 7 || error("fixture field count drift")
        id, sha, start, record, window_size, min_effective, bases = f
        occursin(r"^[A-Za-z0-9_]+$", id) || error("invalid case id")
        occursin(r"^[0-9a-f]{64}$", sha) || error("invalid parameters sha")
        length(bases) in 1:MAX_WINDOW || error("invalid window length")
        window = [get(IUPAC_INDEX, UInt8(c), -1) for c in bases]
        all(0 .<= window .<= 14) || error("invalid IUPAC base in $id")
        push!(cases, (
            id=id,
            sha=sha,
            seed_base=parse(UInt64, sha[1:8]; base=16),
            window_start=parse(Int, start),
            record_index=parse(Int, record),
            window_size=parse(Int, window_size),
            min_effective=parse(Int, min_effective),
            window=window,
        ))
    end
    cases
end

function observed_available(case, metric_index::Int)
    if metric_index < 2
        return length(case.window) == case.window_size && all(base -> 0 <= base <= 3, case.window)
    end
    k = div(metric_index, 2)
    transform = isodd(metric_index) ? rc_transform : reverse_transform
    kmer_imbalance(valid_kmers(case.window, k), transform, case.min_effective).available
end

function golden_draw(case, metric_index::Int, replicate::Int)
    observed_available(case, metric_index) || return -1
    state = null_seed_state(Int(case.seed_base), case.window_start, case.record_index,
                            metric_index, replicate)
    shuffled = copy(case.window)
    null_shuffle!(shuffled, state)
    metric_index < 2 && return null_positional_draw(shuffled, metric_index)
    null_kmer_draw(shuffled, metric_index, case.min_effective)
end

function emit_array(io, ctype::String, name::String, values)
    println(io, "inline constexpr std::array<$ctype, $(length(values))> $name = {{")
    for offset in 1:12:length(values)
        chunk = values[offset:min(offset + 11, end)]
        println(io, "  ", join(chunk, ", "), offset + 11 >= length(values) ? "" : ",")
    end
    println(io, "}};")
end

cases = parse_cases(ARGS[1])
windows = Int32[]
metadata = UInt64[]
expected = Int32[]
for case in cases
    append!(windows, Int32.(case.window))
    append!(windows, fill(Int32(-1), MAX_WINDOW - length(case.window)))
    append!(metadata, UInt64[
        length(case.window), case.window_size, case.seed_base, case.window_start,
        case.record_index, case.min_effective,
    ])
    for metric in 0:METRIC_COUNT-1, replicate in 1:REPLICATES
        push!(expected, Int32(golden_draw(case, metric, replicate)))
    end
end

open(ARGS[2], "w") do io
    println(io, "// Generated by julia/generate_fixture_header.jl; do not edit.")
    println(io, "#pragma once")
    println(io, "#include <array>")
    println(io, "#include <cstdint>")
    println(io, "namespace u250_null_fixture {")
    println(io, "inline constexpr std::uint32_t kCaseCount = $(length(cases));")
    println(io, "inline constexpr std::uint32_t kReplicates = $REPLICATES;")
    println(io, "inline constexpr std::uint32_t kMetricCount = $METRIC_COUNT;")
    println(io, "inline constexpr std::uint32_t kWindowCapacity = $MAX_WINDOW;")
    emit_array(io, "std::int32_t", "kWindows", windows)
    emit_array(io, "std::uint64_t", "kMetadata", metadata)
    emit_array(io, "std::int32_t", "kExpected", expected)
    println(io, "}  // namespace u250_null_fixture")
end

println("U250_NULL_JULIA_FIXTURE_PASS cases=$(length(cases)) metrics=$METRIC_COUNT replicates=$REPLICATES draws=$(length(expected))")
