#!/usr/bin/env julia

length(ARGS) == 3 || error("usage: generate_fixture_header.jl <parameters.json> <cases.tsv> <output.hpp>")
include(joinpath(@__DIR__, "..", "..", "..", "julia", "scripts", "validate_dinucleotide_null.jl"))

const CAPACITY = 16
cases = parse_cases(ARGS[1], ARGS[2])
windows = Int32[]
metadata = UInt64[]
expected = Int32[]
base_index = Dict('A'=>0, 'C'=>1, 'G'=>2, 'T'=>3)

for case in cases
    encoded = Int32[base_index[ch] for ch in case.bases]
    append!(windows, encoded)
    append!(windows, fill(Int32(-1), CAPACITY - length(encoded)))
    push!(metadata, UInt64(length(encoded)))
    push!(metadata, parse(UInt64, case.seed64[1:8]; base=16))
    push!(metadata, parse(UInt64, case.seed64[9:16]; base=16))
    for replicate in 1:REPLICATES
        shuffled = shuffled_sequence(case.bases, case.seed64, replicate)
        draw = Int32[base_index[ch] for ch in shuffled]
        append!(expected, draw)
        append!(expected, fill(Int32(-1), CAPACITY - length(draw)))
    end
end

function emit_array(io, ctype, name, values)
    println(io, "inline constexpr std::array<$ctype, $(length(values))> $name = {{")
    for offset in 1:12:length(values)
        chunk = values[offset:min(offset + 11, end)]
        println(io, "  ", join(chunk, ", "), offset + 11 >= length(values) ? "" : ",")
    end
    println(io, "}};")
end

open(ARGS[3], "w") do io
    println(io, "// Generated by julia/generate_fixture_header.jl; do not edit.")
    println(io, "#pragma once")
    println(io, "#include <array>")
    println(io, "#include <cstdint>")
    println(io, "namespace u250_dinucleotide_fixture {")
    println(io, "inline constexpr std::uint32_t kCaseCount = $(length(cases));")
    println(io, "inline constexpr std::uint32_t kReplicates = $REPLICATES;")
    println(io, "inline constexpr std::uint32_t kCapacity = $CAPACITY;")
    emit_array(io, "std::int32_t", "kWindows", windows)
    emit_array(io, "std::uint64_t", "kMetadata", metadata)
    emit_array(io, "std::int32_t", "kExpected", expected)
    println(io, "}  // namespace u250_dinucleotide_fixture")
end

println("U250_DINUCLEOTIDE_JULIA_FIXTURE_PASS cases=$(length(cases)) replicates=$REPLICATES slots=$(length(expected)) tolerance=0")
